### ISSUE TITLE
including CSS

### ISSUE THREAD

**Issue by serl** [jaap3/django-richtextfield#10]
Hello,
I'm trying to use this to include [summernote](https://github.com/summernote/summernote).

So, apparently I need to include a couple of CSS files alongside the JS.

Is there already a way to do this?

Thanks!

**Comment by jaap3** [comment]
Not yet, but it would be fairly easy to change the widget to also add CSS.

django-richtextfield uses a ["dynamic media property" 
](https://docs.djangoproject.com/en/2.1/topics/forms/media/#media-as-a-dynamic-property) it's defined in [djrichtextfield/widgets.py](https://github.com/jaap3/django-richtextfield/blob/b6ca972aa1d32c63924fe857e98c05c5819972b5/djrichtextfield/widgets.py#L34).

It could be as simple as adding a setting and updating this method to also load CSS alongside the JS.

A PR doing this (including a small change to the README) would be much appreciated.

**Comment by jaap3** [comment]
BTW When/if you manage to get summernote working, I would greatly appreciate it if you could add some of your experience/knowledge to the ["using another editor" section of the docs](https://github.com/jaap3/django-richtextfield#custom-init--using-another-editor)!
