### ISSUE TITLE
Displaying the edit in templates

### ISSUE THREAD

**Issue by mrpbennett** [jaap3/django-richtextfield#16]
This might be a noob questions, I have managed to get the editor to display as one of my fields within my model.

However when I look at that field within my template i get a load of HTML.

```<p>hello this is some notes</p> <p>&nbsp;</p> <p>ohfoehfohwefoihewfohf</p> <p>&nbsp;</p> <p>oehfoehwfoewjfihf</p> <p>be;fh'fg'e]</p> <p>&nbsp;</p> <p>&nbsp;</p> <p>&nbsp;</p>```

This is how i am displaying it within my template

```
<div class="row">
           <div class="col">
                    <p class="client-data text-muted border-bottom">Latest Client Notes:<br>
                        <p class="client-info">{{ object.client_notes }}</p>
                    </p>
                </div>
            </div>
```

How am i able to display the rich text in the template?

**Comment by jaap3** [comment]
It think this is related to issue #4
