### ISSUE TITLE
how can i show the word count in richtextfield ?

### ISSUE THREAD

**Issue by Taher5253** [jaap3/django-richtextfield#17]
I want to show word count in django admin panel richtextfield like ckeditor

This is my model:-

```
class PointsType(models.Model):
     point_name = models.CharField(max_length=100, blank=True, null=True)
     description = RichTextField(blank=True, null=True, field_settings='advanced')
     content = RichTextField(blank=True, null=True)
 def __str__(self):
      return u'{0}'.format(self.point_name)
```

**Comment by Taher5253** [comment]
I want to show word count in django admin panel richtextfield

This is my model:-

class PointsType(models.Model):
    point_name = models.CharField(max_length=100, blank=True, null=True)
    description = RichTextField(blank=True, null=True, field_settings='advanced')
    content = RichTextField(blank=True, null=True)

    def __str__(self):
        return u'{0}'.format(self.point_name)

**Comment by jaap3** [comment]
Sorry this is an issue tracker, not a support forum. Try asking this question on https://stackoverflow.com/
