### ISSUE TITLE
Difficulty with RichTextField

### ISSUE THREAD

**Issue by cobalsky** [jaap3/django-richtextfield#19]
I happen to implement RichTextField but when I put it in a div with truncatechars:10 | safe 
it dislocates my sections of my site

![Captura de pantalla (2)](https://user-images.githubusercontent.com/62456079/82135149-d9b31d80-97c4-11ea-989c-ea6d685e6ca4.png)

**Comment by jaap3** [comment]
Since you are truncating HTML you'll want to use `truncatechars_html` (https://docs.djangoproject.com/en/3.0/ref/templates/builtins/#truncatechars-html)
