### ISSUE TITLE
Referer head is missing

### ISSUE THREAD

**Issue by andreashhpetersen** [jaap3/django-richtextfield#24]
Using TinyMCE with an API-key, I get the following warning message in all my rendered textfields:

> We’re unable to check your domain because the referer header is missing. Please read the Guide on how to ensure your referer header is present, so we can then customize your editor experience.

This comes from TinyMCE, and I guess it is because the header script is missing `referrerpolicy="origin"` (according to the tinymce doc the header should include `<script src="//cdn.tiny.cl..." refererrerpolicy="origin"></script>`).

Can I add that via the configuration settings somehow?

**Comment by andreashhpetersen** [comment]
Thanks! I tried both solutions, and both of them fixed my issue in Chrome, but in my primary browser, Firefox, I still get the message. However, I suspect that has to do with some of the privacy plugins that I have installed. Chrome is totally clean.

**Comment by jaap3** [comment]
I wouldn't mind a pull request that adds this to the documentation ;)

**Comment by andreashhpetersen** [comment]
Sure! I'll get to it one of the coming days :)
