### ISSUE TITLE
Displaying the widget outside of admin

### ISSUE THREAD

**Issue by justinline** [jaap3/django-richtextfield#4]
Heya,

Firstly, awesome plugin, really useful! :+1: 

Apologies if this is an error on my part, but I was having difficulty getting the widget to show up outside of the Django Admin - my current workaround is by linking to admin jQuery files in the template:
`<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>`
`<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>`
otherwise init.js throws an error saying django.jQuery is not defined.

I also have to add:
`{{form.media}}` 
before the form in order to get the widget urls on the page. May be helpful to add to the docs?

I'm happy to help fix if it is an issue but I don't really understand the use of django.jQuery as I've never really used jQuery.

**Comment by jaap3** [comment]
Yes, it seems that I never really tested the widget outside of Django's admin site. Glad to hear that you at least got it working.

The dependency on `django.jQuery` is `inits.js` (https://github.com/jaap3/django-richtextfield/blob/master/djrichtextfield/templates/djrichtextfield/init.js). This code hasn't been touched in years, and is very admin specific. It can definitely be improved to be more generic and maybe even jQuery free.

I currently don't have the time to do this however. So a PR with improved code and docs would be very welcome.

**Comment by jaap3** [comment]
This has been partially address by PR #5, which adds the admin jQuery dependencies to the media definition by default.

I'll leave this ticket open, as the bit about adding `{{ form.media }}` hasn't been added to the docs and, in an ideal situation, there wouldn't be any dependencies on scripts shipped with `django.contrib.admin`.
